console.log(108*5);
console.log(Math.PI);
console.log(typeof '1444');
console.log(parseInt('172') + 34);
console.log(isNaN('HELLO WORLD'));
console.log(+'66');
console.log('Abomination'. length);
console.log('Cornelius'. charAt(3));
console.log('hello' + 'world' + "!");
console.log("Raise amm Raise amm!!!". toUpperCase());
